### ISSUE TITLE
Exchange in confirmed mode does not confirm - why?

### ISSUE THREAD

**Issue by goloroden** [postwait/node-amqp#134]
I'm not sure whether I simply misunderstood confirm mode, or if there is a bug in node-amqp regarding confirm mode ...

Could you be so kind to take a look at http://stackoverflow.com/questions/12662413/rabbitmq-and-node-amqp-exchange-in-confirmed-mode-does-not-confirm-why ?

**Comment by jbyrneie** [comment]
All the above comments/code are creating the Exchange. I am using "amqp 0.2.4". My Exchange already exists. I do not get a callback when I publish a message to the Exchange. How can I determine that the message has been successful or failed when published

**Comment by jacksonhull** [comment]
if you are struggling with this, try adding
`persistent: false`
to your publish command
