### ISSUE TITLE
Heartbeats sent after connection has closed

### ISSUE THREAD

**Issue by jus101** [postwait/node-amqp#156]
``` javascript
this.connection = amqp.createConnection({heartbeat: 10, ...});
```

later:

``` javascript
this.connection.end();
```

A few moments later, the following exception is raised because the timeouts to send a heartbeat fire.

events.js:48
        throw arguments[1]; // Unhandled 'error' event
        ^
Error: This socket is closed.
    at Connection._write (net.js:474:19)
    at Connection.write (net.js:466:15)
    at Connection.heartbeat (/var/home/app/node_modules/amqp/amqp.js:1169:8)
    at Object.<anonymous> ((var/home/app/node_modules/amqp/amqp.js:1180:12)
    at Timer.ontimeout (timers.js:94:19)

**Comment by CacheControl** [comment]
For anyone finding this issue, parts are still relevant.  We've had to set the following when disconnecting, to prevent the event loop staying open until the heartbeat fails twice:

```js
// disable reconnection
connection.setImplOptions({ reconnect: false });

// disable heartbeat, otherwise the heartbeat keeps the event loop open
this.connection.options.heartbeat = 0;

// finally, disconnect
this.connection.disconnect();
```
