### ISSUE TITLE
Is there a way to check queue size?

### ISSUE THREAD

**Issue by crzidea** [postwait/node-amqp#336]
Checking queue size and not consume messages, like [this](http://stackoverflow.com/questions/1038318/check-rabbitmq-queue-size-from-client).
I just need a node-amqp version.

**Comment by soichih** [comment]
This would do

```
    acon.queue('myqueue', {passive: true}, (q, message_count, consumer_count)=>{
        console.log("message_count:"+message_count);
    });
```
